In [1]:
import numpy as np
print(np.__version__)

2.3.2


### Creating 1D Array and properties

In [25]:
arr1d = np.array([1,14,67])
arr1d = np.arange(1,10)
arr1d = np.random.randint(1,10,(5))
print("Array value ", arr1d)
print("Type is", type(arr1d))
print("Shape is", arr1d.shape, np.shape(arr1d))
print("Size is", arr1d.size, np.size(arr1d))
print("Length is", len(arr1d))
print("Data type is", arr1d.dtype)
print("Itemsize is", arr1d.itemsize)
print("Size is", arr1d.nbytes)

Array value  [3 9 6 4 4]
Type is <class 'numpy.ndarray'>
Shape is (5,) (5,)
Size is 5 5
Length is 5
Data type is int64
Itemsize is 8
Size is 40


### creating arrays with different ways

In [41]:
print("Example for np.zeroes((4,5))\n", np.zeros((4,5)))
print(np.ones((4,5)))
print(np.full((3,4),100))
print(np.eye(5))
print(np.arange(1,10,2))
print(np.linspace(1,10,2))
print(np.random.random((4,5)))
print(np.random.rand(4,5))
print(np.random.randint(1,10,(3,4)))
print(np.empty((4,5)))

Example for np.zeroes((4,5))
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1 3 5 7 9]
[ 1. 10.]
[[0.08070639 0.62536951 0.06258703 0.31364271 0.00325352]
 [0.8504796  0.41718988 0.206601   0.87919264 0.72714945]
 [0.91138101 0.9418719  0.82368619 0.42061959 0.30301563]
 [0.02872892 0.8585925  0.69397975 0.21263803 0.2559836 ]]
[[0.37731671 0.40156292 0.54595116 0.85634823 0.72317551]
 [0.98982208 0.15652979 0.96647209 0.93227835 0.12811642]
 [0.69506638 0.05516474 0.51705023 0.73808202 0.31149219]
 [0.44905459 0.95561431 0.21963796 0.14891813 0.95670787]]
[[9 1 1 6]
 [8 1 5 3]
 [4 2 7 7]]
[[0.37731671 0.40156292 0.54595116 0.85634823 0.72317551]
 [0.98982208 0.15652979 0.96647209 0.93227835 0.12811642]
 [0.69506638 0.05516474 0.51705023 0.

### Reshape, Flatten, Ravel, Transpose

In [56]:
arr = np.arange(1,10)
print("Initial array is", arr)
print("reshape array is", arr.reshape(3,-1))
print("reshape array is", arr.reshape(3,3))
print("reshape array is", arr.reshape(9))
print("reshape array is", np.reshape(arr,(3,3)))
print("Flatten is", arr.flatten())
print("Ravel is", arr.ravel())
print("Original array is", arr)

arr2d = np.random.randint(1,10, (2,4))
print("\nOriginal array is", arr2d)
print("Transpose 2d array is", arr2d.T)


Initial array is [1 2 3 4 5 6 7 8 9]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape array is [1 2 3 4 5 6 7 8 9]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flatten is [1 2 3 4 5 6 7 8 9]
Ravel is [1 2 3 4 5 6 7 8 9]
Original array is [1 2 3 4 5 6 7 8 9]

Original array is [[4 9 9 3]
 [8 3 9 1]]
Transpose 2d array is [[4 8]
 [9 3]
 [9 9]
 [3 1]]


### Indexing and Slicing in 1D Arrays

In [106]:
arr1d = np.random.randint(1,100,10)
print("Array is", arr1d)
print("Value of arr1d[3] is", arr1d[3])
print("Value of arr1d[-3] is", arr1d[-3])
print("Value of arr1d[3:] is", arr1d[3:])
print("Value of arr1d[::2] is", arr1d[::2])
print("Value of arr1d[::-1] is", arr1d[::-1])
print("Original Array is", arr1d)

Array is [38 41 13 60 69 86 84 34  4  7]
Value of arr1d[3] is 60
Value of arr1d[-3] is 34
Value of arr1d[3:] is [60 69 86 84 34  4  7]
Value of arr1d[::2] is [38 13 69 84  4]
Value of arr1d[::-1] is [ 7  4 34 84 86 69 60 13 41 38]
Original Array is [38 41 13 60 69 86 84 34  4  7]


### Indexing and Slicing for 2d Arrays

In [102]:
arr2d = np.random.randint(1,100,(4,5))
print("Value of array is\n", arr2d)
print("value of arr2d[0] is \n", arr2d[0])
print("value of arr2d[0:] is \n", arr2d[0:])
print("value of arr2d[:,1] is \n", arr2d[:,1])
print("value of arr2d[:,1:] is \n", arr2d[:,1:])
print(arr2d[1:3,1:3])

Value of array is
 [[72 95 26  4 81]
 [87  7 33 81 83]
 [ 9 24 66 37 66]
 [50 43 14 84 66]]
value of arr2d[0] is 
 [72 95 26  4 81]
value of arr2d[0:] is 
 [[72 95 26  4 81]
 [87  7 33 81 83]
 [ 9 24 66 37 66]
 [50 43 14 84 66]]
value of arr2d[:,1] is 
 [95  7 24 43]
value of arr2d[:,1:] is 
 [[95 26  4 81]
 [ 7 33 81 83]
 [24 66 37 66]
 [43 14 84 66]]
[[ 7 33]
 [24 66]]


### Sorting 1d array

In [107]:
arr1d = np.array([13,43,4,867,55])
print("Original array is", arr1d)
print("Sorting is", np.sort(arr1d))
print("Original array is", arr1d)
print("Sorting is", arr1d.sort()) # it sorts the original array
print("Original array is", arr1d)

Original array is [ 13  43   4 867  55]
Sorting is [  4  13  43  55 867]
Original array is [ 13  43   4 867  55]
Sorting is None
Original array is [  4  13  43  55 867]


### Sort 2d Arrays

In [112]:
arr2d = np.array([[3,1],[2,3],[1,2]])
print("Original array is\n", arr2d)
print("Sort array column wise\n", np.sort(arr2d,axis=0))
print("Sort array row wise\n", np.sort(arr2d,axis=1))
print("Sort array default\n", np.sort(arr2d))

Original array is
 [[3 1]
 [2 3]
 [1 2]]
Sort array column wise
 [[1 1]
 [2 2]
 [3 3]]
Sort array row wise
 [[1 3]
 [2 3]
 [1 2]]
Sort array default
 [[1 3]
 [2 3]
 [1 2]]
