In [ ]:
import numpy as np # pip install numpy
print(np.__version__) # to get version

2.3.2


### Boolean filter

In [14]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(arr1d % 2 == 0)
print(arr1d[arr1d % 2 == 0])
print(arr1d > 5)
print(arr1d[(arr1d > 5)])
print((arr1d > 4) & (arr1d < 10))
print(arr1d[(arr1d > 4) & (arr1d < 10)])
print(~(arr1d > 4) & (arr1d < 10))

[False  True  True False  True False  True  True]
[ 4  6  8 10  6]
[False False  True  True  True  True  True  True]
[ 6  7  8  9 10  6]
[False False  True  True  True  True False  True]
[6 7 8 9 6]
[ True  True False False False False False False]


### where filter

In [20]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(np.where(arr1d > 6))
print(arr1d[np.where(arr1d > 6)])
print(np.where(arr1d > 6, True, False))

(array([3, 4, 5, 6]),)
[ 7  8  9 10]
[False False False  True  True  True  True False]


### vectorisation

In [4]:
arr = np.array(["john","doe"])
vec_up = np.vectorize(str.lower)
print(vec_up(arr))


['john' 'doe']


### insert
### delete
### split (np.split(), np.hsplit(), np.vsplit())

In [24]:
arr = np.array([1,5,6,8,])
print(np.insert(arr, 1, 15))
print(np.delete(arr, 0))
print(np.split(arr,2))

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8]])

print(np.split(arr, 2, axis=1))



[ 1 15  5  6  8]
[5 6 8]
[array([1, 5]), array([6, 8])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
