In [2]:
import numpy as np
print(np.__version__)

2.3.2


In [16]:
arr0 = np.array(5)
arr1 = np.arange(1,10,2)
arr2 = np.random.randint(10,100, (3,4))

print("************* 0D Array Properties ***********")
print("Value of arr0", arr0)
print("Type of arr0", type(arr0))
# print("Length of arr0", len(arr0)) # TypeError: len() of unsized object
print("Dimension of arr0", arr0.ndim)
print("Shape of arr0", arr0.shape)
print("Size of arr0", arr0.size)
print("ItemSize of arr0", arr0.itemsize)
print("Bytes of arr0", arr0.nbytes)

print("\n************* 1D Array Properties ***********")
print("Value of arr1", arr1)
print("Type of arr01", arr0.dtype)
print("Type of arr1", type(arr1))
print("Length of arr1", len(arr1))
print("Dimension of arr1", arr1.ndim)
print("Shape of arr1", arr1.shape)
print("Size of arr1", arr1.size)
print("ItemSize of arr1", arr1.itemsize)
print("Bytes of arr1", arr1.nbytes)
print("Type of arr01", arr1.dtype)

print("\n************* 2D Array Properties ***********")
print("Value of arr2\n", arr2)
print("Type of arr2", type(arr2))
print("Length of arr2", len(arr2))
print("Dimension of arr2", arr2.ndim)
print("Shape of arr2", arr2.shape)
print("Size of arr2", arr2.size)
print("ItemSize of arr2", arr2.itemsize)
print("Bytes of arr2", arr2.nbytes)
print("Type of arr02", arr2.dtype)



************* 0D Array Properties ***********
Value of arr0 5
Type of arr0 <class 'numpy.ndarray'>
Dimension of arr0 0
Shape of arr0 ()
Size of arr0 1
ItemSize of arr0 8
Bytes of arr0 8

************* 1D Array Properties ***********
Value of arr1 [1 3 5 7 9]
Type of arr01 int64
Type of arr1 <class 'numpy.ndarray'>
Length of arr1 5
Dimension of arr1 1
Shape of arr1 (5,)
Size of arr1 5
ItemSize of arr1 8
Bytes of arr1 40
Type of arr01 int64

************* 2D Array Properties ***********
Value of arr2
 [[51 88 43 30]
 [47 64 45 45]
 [82 84 99 20]]
Type of arr2 <class 'numpy.ndarray'>
Length of arr2 3
Dimension of arr2 2
Shape of arr2 (3, 4)
Size of arr2 12
ItemSize of arr2 8
Bytes of arr2 96
Type of arr02 int64


### Creating arrays using different methods

In [31]:
arr = np.zeros((2,3))
print(arr)

arr = np.ones((3,2))
print(arr)

arr = np.full((3,2),999)
print(arr)

print(np.eye(5))

print(np.empty((3,2)))

print(np.random.random((2,3)))
print(np.random.rand(2,3))
print(np.random.randint(10,200,(2,4)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[999 999]
 [999 999]
 [999 999]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.85707744 0.53359969 0.09861814]
 [0.82658826 0.12514007 0.16701882]]
[[0.57027526 0.43103291 0.57031703]
 [0.1532957  0.45763956 0.1128986 ]]
[[ 45  47  15  39]
 [120  58 125  44]]


### reshape, flatten, ravel transpose (T) 

In [38]:
arr = np.arange(1,10)
print(arr.reshape(3,-1)) # view
print(arr.reshape(3,3))
# print(arr.reshape(3,2)) # ValueError: cannot reshape array of size 9 into shape (3,2)

arr2 = np.random.randint(1,10,(3,4))
print(arr2)
print(arr2.T)
print(arr2.flatten()) # copy
print(arr2.ravel()) # view

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 9 3 4]
 [4 7 3 9]
 [8 4 7 1]]
[[3 4 8]
 [9 7 4]
 [3 3 7]
 [4 9 1]]
[3 9 3 4 4 7 3 9 8 4 7 1]
[3 9 3 4 4 7 3 9 8 4 7 1]


## dtype and type change (astype)

In [45]:
arr_a = np.array([1,3,4,5],dtype=float)
print(arr_a.dtype)
arr_b = np.array([1,3,4,5],dtype=np.float64)
print(arr_b.dtype)
print(arr_b)
print(arr_b.astype(int))
print(arr_b)
print(arr_b.astype(np.int8))

float64
float64
[1. 3. 4. 5.]
[1 3 4 5]
[1. 3. 4. 5.]
[1 3 4 5]


### Indexing, Slicing and fancy indexing

In [54]:
arr1 = np.random.randint(10,100,(5))
print(arr1)
print(arr1[0],arr[-1])
print(arr1[1:])
print(arr1[:3])
print(arr1[:])
print(arr1[::-1])

[56 30 76 28 72]
56 9
[30 76 28 72]
[56 30 76]
[56 30 76 28 72]
[72 28 76 30 56]


In [78]:
arr2 = np.random.randint(20,40,(2,3))
print(arr2)
# print(arr2[:])
# print(arr2[:,:])
# print(arr2[1]) # [37 38 26] index dimension reduced
# print(arr2[1:]) # [[37 38 26]] slice dimemsion preserved
# print(arr2[1:,1:])
# print(arr2[1:,2:])
# print(arr2[1:,2]) # dimension reduced as index used
# print(arr2[1:2,1:2])
print(arr2[1, 1]) # scalar 
print(arr2[[1], [1]]) # array([scalar])


[[25 37 38]
 [24 27 33]]
27
[27]


In [85]:
arr1 = np.random.randint(10,100,(5))
# print(arr1)
# print(arr1[[1,2]])

arr2 = np.random.randint(20,40,(2,3))
print(arr2)
# print(arr2[[1],[2]])
# print(arr2[[0,1],[2]]) # NumPy broadcast [2] as [2,2]
# print(arr2[[0,1],[1,2]])
print(arr2[:, [1, 2]])


[[33 24 29]
 [33 39 31]]
[[24 29]
 [39 31]]


### Sort 1d and 2d Array

In [96]:
arr1 = np.random.randint(10,40,7)
print(arr1)
print(np.sort(arr1))
print(arr1)
print("Sorting is", arr1.sort()) # it sorts the original array and it returns None
print(arr1)

arr2d = np.array([[3,1],[2,3],[1,2]])
print("Original array is\n", arr2d)
print("Sort array column wise\n", np.sort(arr2d,axis=0))
print("Sort array row wise\n", np.sort(arr2d,axis=1))
print("Sort array default\n", np.sort(arr2d)) # row wise
print("Sort array column wise\n", np.sort(arr2d,axis=None)) # flatten the ouput


[35 15 25 33 12 33 36]
[12 15 25 33 33 35 36]
[35 15 25 33 12 33 36]
Sorting is None
[12 15 25 33 33 35 36]
Original array is
 [[3 1]
 [2 3]
 [1 2]]
Sort array column wise
 [[1 1]
 [2 2]
 [3 3]]
Sort array row wise
 [[1 3]
 [2 3]
 [1 2]]
Sort array default
 [[1 3]
 [2 3]
 [1 2]]
Sort array column wise
 [1 1 2 2 3 3]


### Sum 1d and 2d Array

In [92]:
arr1 = np.random.randint(10,40,7)
print(arr1)
print(np.sum(arr1))

arr2d = np.array([[3,1],[2,3],[1,2]])
print("Original array is\n", arr2d)
print("Sum array column wise\n", np.sum(arr2d,axis=0))
print("Sum array row wise\n", np.sum(arr2d,axis=1))
print("Sum array default\n", np.sum(arr2d)) # default flatten the array and then sum

[12 25 10 26 15 17 11]
116
Original array is
 [[3 1]
 [2 3]
 [1 2]]
Sum array column wise
 [6 6]
Sum array row wise
 [4 5 3]
Sum array default
 12


### mathematical operations

In [93]:
arr = np.random.randint(10,60,8)
print(arr)
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

[59 27 31 26 34 24 19 29]
249
59
19
31.125
11.351624333107575
128.859375


### Mathematical functions

In [94]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,3,1])
print(arr1 * 2)
print(arr1 * arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

arr3 = np.random.randint(10,50,(3,3))
print("value of arr3 is \n",arr3)
print(arr3 * 2)
print(arr3 * arr1)

[ 6  8 10]
[ 6 12  5]
[5 7 6]
[1 1 4]
[1.5        1.33333333 5.        ]
[ 9 64  5]
value of arr3 is 
 [[39 21 16]
 [27 37 12]
 [15 44 10]]
[[78 42 32]
 [54 74 24]
 [30 88 20]]
[[117  84  80]
 [ 81 148  60]
 [ 45 176  50]]


### vstack and hstack

In [99]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5],
              [6]])
print(np.hstack((a, b)))
print(np.vstack((a, b.T)))


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]]


### append, concatenate, insert

In [100]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
# print(np.append(arr1,arr2))
# print(np.concatenate((arr1,arr2))) # arrays passed as tuple

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
print(np.append(arr1,arr2))
print("Output of append\n",np.append(arr1,arr2,axis=0))
print("Output of concatenate\n",np.concatenate((arr1,arr2),axis=0))
print(np.append(arr1,arr2,axis=1))
print(np.concatenate((arr1,arr2),axis=1))

arr = np.array([[1,2],[3,4]])
print(np.insert(arr,0,[5,6],axis=0))
print(np.insert(arr,1,[5,6],axis=0))
print(np.insert(arr,2,[5,6],axis=0))
print(np.insert(arr,0,[5,6],axis=1)) # NumPy reshapes it internally to (1, 2)
print(np.insert(arr,2,[5,6],axis=1))
print(np.insert(arr,2,[5,6],axis=None))
print(np.concatenate((arr,[[5,6]]),axis=0))
print(np.concatenate((arr,[[5],[6]]),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6]
Output of append
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Output of concatenate
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[5 6]
 [1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[5 1 2]
 [6 3 4]]
[[1 2 5]
 [3 4 6]]
[1 2 5 6 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


### Insert and delete

In [116]:
# arr1 = np.array([1,5,6,7,8,0])
# print(arr1)
# print(np.delete(arr1,3))
# print(np.delete(arr1,[1,3]))
# print(np.insert(arr1,3,100))
# print(np.insert(arr1,3,[100,101])) # Insert muliple values
# print(np.insert(arr1,[3,5],[100,101])) # Insert at multiple positions
# print(arr1)

arr2 = np.random.randint(1,10,(2,3))
print(arr2)
# print(np.delete(arr2,1)) # default axix=None which flatten the array 
# print(np.delete(arr2,1,axis=1)) # to delete the column
# print(np.delete(arr2,1,axis=0)) # to delete the row
print(np.insert(arr2,0,[1, 1, 1], axis=0))
print(np.insert(arr2,0,[1, 1], axis=1))

[[9 4 7]
 [9 1 9]]
[[1 1 1]
 [9 4 7]
 [9 1 9]]
[[1 9 4 7]
 [1 9 1 9]]


### boolean filter

In [120]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(arr1d % 2 == 0)
print(arr1d[arr1d % 2 == 0])
print(arr1d > 5)
print(arr1d[(arr1d > 5)])
print((arr1d > 4) & (arr1d < 10))
print(arr1d[(arr1d > 4) & (arr1d < 10)])
print(~(arr1d > 4) & (arr1d < 10))

[False  True  True False  True False  True  True]
[ 4  6  8 10  6]
[False False  True  True  True  True  True  True]
[ 6  7  8  9 10  6]
[False False  True  True  True  True False  True]
[6 7 8 9 6]
[ True  True False False False False False False]


### where filter

In [121]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(np.where(arr1d > 6))
print(arr1d[np.where(arr1d > 6)])
print(np.where(arr1d > 6, True, False))

(array([3, 4, 5, 6]),)
[ 7  8  9 10]
[False False False  True  True  True  True False]


### split

In [119]:
a = np.array([10, 20, 30, 40])
print(np.split(a, 2))
print(np.split(a, [1, 3])) # Split at indices


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(np.hsplit(arr, 2))

[array([10, 20]), array([30, 40])]
[array([10]), array([20, 30]), array([40])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### vectorisation

In [122]:
arr = np.array(["john","doe"])
vec_up = np.vectorize(str.lower)
print(vec_up(arr))

['john' 'doe']
