In [4]:
import numpy as np
print(np.__version__)

2.3.2


create arrays \
Practice with Attributes  \
Practice creating numpy arrays using standard methods  \
Indexing and Slicing  \
Fancy Indexing \
Reshaping, flatten, ravel  \
sorting  \
Filter and Filter with mask  \
Filter with where clause  \
concatenate, vstack, hstack \
np.delete \


### Array creation

In [5]:
array_0 = np.array(10)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

10
<class 'numpy.ndarray'>
0
()
int64
1
8
8


In [6]:
array_0 = np.arange(1,10,1)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(9,)
int64
9
8
72


In [7]:
array_2 = np.random.randint(1,10,(2,3))
print(array_2)
print(type(array_2))
print(array_2.ndim)
print(array_2.shape)
print(array_2.dtype)
print(array_2.size)
print(array_2.itemsize)
print(array_2.nbytes)

[[5 8 7]
 [3 1 3]]
<class 'numpy.ndarray'>
2
(2, 3)
int64
6
8
48


In [8]:
array_zeros = np.zeros((5,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
array_ones = np.ones((5,4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
array_full = np.full((3,4),10)
array_full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [11]:
array_arange = np.arange(1,10,2)
array_arange

array([1, 3, 5, 7, 9])

In [12]:
array_linspace = np.linspace(1,10,2)
array_linspace

array([ 1., 10.])

In [13]:
array_random_random = np.random.random((2,4))
array_random_random

array([[0.76851493, 0.25212948, 0.35679151, 0.48583922],
       [0.47213537, 0.86447429, 0.02968279, 0.20707333]])

In [14]:
array_random_rand = np.random.rand(2,4)
array_random_rand

array([[0.21523315, 0.84508285, 0.97355386, 0.23817221],
       [0.11908363, 0.50716979, 0.75337413, 0.91946431]])

In [47]:
array_random_randint = np.random.randint(1,5,(5,6))
array_random_randint

array([[4, 2, 2, 4, 1, 3],
       [3, 3, 1, 3, 1, 3],
       [1, 4, 2, 3, 3, 1],
       [4, 3, 1, 3, 1, 2],
       [4, 4, 2, 1, 4, 2]])

In [51]:
array_eye = np.eye(4,4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
array_empty = np.empty((3,5))
array_empty

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [61]:
print(array_empty.shape)

(3, 5)


In [60]:
print(array_empty[2][4])

0.4472135954999579


In [68]:
print(array_empty[2,4])
print(array_empty[2,4:])
print(array_empty[2:,3:])

0.4472135954999579
[0.4472136]
[[0.73029674 0.4472136 ]]


In [74]:
print(array_empty)
fancy_indexing = [2,2]
print("****")
print(array_empty[fancy_indexing])

[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]
****
[[0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


In [75]:
print(array_empty)
fancy_indexing = [[2,2],[1,2]]
print(array_empty[fancy_indexing])

[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]
[[[0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]
  [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]

 [[0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
  [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]]


In [76]:
array_1d = np.array([35,2,6,78,235,7,4])
print(np.sort(array_1d))

[  2   4   6   7  35  78 235]


In [81]:
array_2d = np.array([[2,1],[3,2],[1,3]])
print(np.sort(array_2d))
print(np.sort(array_2d,axis=0))
print(np.sort(array_2d,axis=1))

[[1 2]
 [2 3]
 [1 3]]
[[1 1]
 [2 2]
 [3 3]]
[[1 2]
 [2 3]
 [1 3]]


In [ ]:
array_1d = np.array([10,3,5,7,1,3])
print(array_1d[array_1d > 3])
print(array_1d > 3)
bool_array = array_1d > 3
print(~bool_array)
print(array_1d[~bool_array])

[10  5  7]
[ True False  True  True False False]
[False  True False False  True  True]
[3 1 3]


In [ ]:
# where


In [90]:
array_1d = np.array([10,3,5,7,1,3])
print(np.sum(array_1d))
print(np.max(array_1d))
print(np.min(array_1d))
print(np.std(array_1d))
print(np.var(array_1d))

29
10
1
2.9674156357941426
8.805555555555555
