In [1]:
import numpy as np
print(np.__version__)

2.3.2


### Array creation

In [5]:
array_0 = np.array(10)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

10
<class 'numpy.ndarray'>
0
()
int64
1
8
8


In [ ]:
array_0 = np.arange(1,10,1)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(9,)
int64
9
8
72


In [6]:
array_2 = np.random.randint(1,10,(2,3))
print(array_2)
print(type(array_2))
print(array_2.ndim)
print(array_2.shape)
print(array_2.dtype)
print(array_2.size)
print(array_2.itemsize)
print(array_2.nbytes)

[[1 5 5]
 [6 4 9]]
<class 'numpy.ndarray'>
2
(2, 3)
int64
6
8
48
