In [2]:
import numpy as np

array_a = np.array([4,5,6,])
print(array_a)

array_b = np.zeros((5,3), dtype=np.int64) # dtype="int64"
print(type(array_b))
print(array_b)
print(array_b.shape)
print(array_b.size)
print(array_b.dtype)
print(array_b.itemsize)
print(array_b.ndim)
print(array_b[1,1])

[4 5 6]
<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(5, 3)
15
int64
8
2
0


In [3]:
print(np.__version__)

2.3.2


In [13]:
myarray = np.ones((4,5))
print(myarray)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
myarray = np.full((2,3),5)
print(myarray)

[[5 5 5]
 [5 5 5]]


In [16]:
myarray = np.linspace(1,5,10)
print(myarray)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [18]:
myarray = np.arange(1,10,2)
myarray

array([1, 3, 5, 7, 9])

In [29]:
myarray = np.eye(5,5,k=5)
myarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
myarray = np.empty((4,5))
myarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
myarray = np.array([[4,5,6],[10,56,21]])
print(myarray.sum())
print(myarray.mean())
print(myarray.max())
print(myarray.min())
print(myarray.sum(axis=0))
print(myarray.sum(axis=1))

102
17.0
56
4
[14 61 27]
[15 87]


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[1,1])
print(a[1:])

5


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[[0,2]]) # fancy indexing

[[1 2 3]
 [7 8 9]]


In [11]:
arr = np.array([[1,np.nan,4,np.nan],[np.inf,0,1,np.nan]])
print(arr.dtype)
print(np.isnan(arr).sum())
print(np.isinf(arr))

float64
3
[[False False False False]
 [ True False False False]]
