In [ ]:
import numpy as np # pip install numpy
print(np.__version__) # to get version

2.3.2


### Creating 1D Array and properties

In [ ]:
arr1d = np.array([1,14,67])
arr1d = np.arange(1,10) # start,end(exclusive),step
arr1d = np.random.randint(1,10,(5))
print("Array value ", arr1d)
print("Type is", type(arr1d))
print("Shape is", arr1d.shape, np.shape(arr1d))
print("Size is", arr1d.size, np.size(arr1d))
print("Length is", len(arr1d))
print("Data type is", arr1d.dtype)
print("Itemsize is", arr1d.itemsize)
print("Size is", arr1d.nbytes)

Array value  [3 9 6 4 4]
Type is <class 'numpy.ndarray'>
Shape is (5,) (5,)
Size is 5 5
Length is 5
Data type is int64
Itemsize is 8
Size is 40


### creating arrays with different ways

In [41]:
print("Example for np.zeroes((4,5))\n", np.zeros((4,5)))
print(np.ones((4,5)))
print(np.full((3,4),100))
print(np.eye(5))
print(np.arange(1,10,2))
print(np.linspace(1,10,2))
print(np.random.random((4,5)))
print(np.random.rand(4,5))
print(np.random.randint(1,10,(3,4)))
print(np.empty((4,5)))

Example for np.zeroes((4,5))
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1 3 5 7 9]
[ 1. 10.]
[[0.08070639 0.62536951 0.06258703 0.31364271 0.00325352]
 [0.8504796  0.41718988 0.206601   0.87919264 0.72714945]
 [0.91138101 0.9418719  0.82368619 0.42061959 0.30301563]
 [0.02872892 0.8585925  0.69397975 0.21263803 0.2559836 ]]
[[0.37731671 0.40156292 0.54595116 0.85634823 0.72317551]
 [0.98982208 0.15652979 0.96647209 0.93227835 0.12811642]
 [0.69506638 0.05516474 0.51705023 0.73808202 0.31149219]
 [0.44905459 0.95561431 0.21963796 0.14891813 0.95670787]]
[[9 1 1 6]
 [8 1 5 3]
 [4 2 7 7]]
[[0.37731671 0.40156292 0.54595116 0.85634823 0.72317551]
 [0.98982208 0.15652979 0.96647209 0.93227835 0.12811642]
 [0.69506638 0.05516474 0.51705023 0.

### Reshape, Flatten, Ravel, Transpose

In [56]:
arr = np.arange(1,10)
print("Initial array is", arr)
print("reshape array is", arr.reshape(3,-1))
print("reshape array is", arr.reshape(3,3))
print("reshape array is", arr.reshape(9))
print("reshape array is", np.reshape(arr,(3,3)))
print("Flatten is", arr.flatten())
print("Ravel is", arr.ravel())
print("Original array is", arr)

arr2d = np.random.randint(1,10, (2,4))
print("\nOriginal array is", arr2d)
print("Transpose 2d array is", arr2d.T)


Initial array is [1 2 3 4 5 6 7 8 9]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape array is [1 2 3 4 5 6 7 8 9]
reshape array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flatten is [1 2 3 4 5 6 7 8 9]
Ravel is [1 2 3 4 5 6 7 8 9]
Original array is [1 2 3 4 5 6 7 8 9]

Original array is [[4 9 9 3]
 [8 3 9 1]]
Transpose 2d array is [[4 8]
 [9 3]
 [9 9]
 [3 1]]


### Indexing and Slicing in 1D Arrays

In [106]:
arr1d = np.random.randint(1,100,10)
print("Array is", arr1d)
print("Value of arr1d[3] is", arr1d[3])
print("Value of arr1d[-3] is", arr1d[-3])
print("Value of arr1d[3:] is", arr1d[3:])
print("Value of arr1d[::2] is", arr1d[::2])
print("Value of arr1d[::-1] is", arr1d[::-1])
print("Original Array is", arr1d)

Array is [38 41 13 60 69 86 84 34  4  7]
Value of arr1d[3] is 60
Value of arr1d[-3] is 34
Value of arr1d[3:] is [60 69 86 84 34  4  7]
Value of arr1d[::2] is [38 13 69 84  4]
Value of arr1d[::-1] is [ 7  4 34 84 86 69 60 13 41 38]
Original Array is [38 41 13 60 69 86 84 34  4  7]


### Indexing and Slicing for 2d Arrays

In [102]:
arr2d = np.random.randint(1,100,(4,5))
print("Value of array is\n", arr2d)
print("value of arr2d[0] is \n", arr2d[0])
print("value of arr2d[0:] is \n", arr2d[0:])
print("value of arr2d[:,1] is \n", arr2d[:,1])
print("value of arr2d[:,1:] is \n", arr2d[:,1:])
print(arr2d[1:3,1:3])

Value of array is
 [[72 95 26  4 81]
 [87  7 33 81 83]
 [ 9 24 66 37 66]
 [50 43 14 84 66]]
value of arr2d[0] is 
 [72 95 26  4 81]
value of arr2d[0:] is 
 [[72 95 26  4 81]
 [87  7 33 81 83]
 [ 9 24 66 37 66]
 [50 43 14 84 66]]
value of arr2d[:,1] is 
 [95  7 24 43]
value of arr2d[:,1:] is 
 [[95 26  4 81]
 [ 7 33 81 83]
 [24 66 37 66]
 [43 14 84 66]]
[[ 7 33]
 [24 66]]


### Sorting 1d array

In [107]:
arr1d = np.array([13,43,4,867,55])
print("Original array is", arr1d)
print("Sorting is", np.sort(arr1d))
print("Original array is", arr1d)
print("Sorting is", arr1d.sort()) # it sorts the original array
print("Original array is", arr1d)

Original array is [ 13  43   4 867  55]
Sorting is [  4  13  43  55 867]
Original array is [ 13  43   4 867  55]
Sorting is None
Original array is [  4  13  43  55 867]


### Sort 2d Arrays

In [6]:
arr2d = np.array([[3,1],[2,3],[1,2]])
print("Original array is\n", arr2d)
print("Sort array column wise\n", np.sort(arr2d,axis=0))
print("Sort array row wise\n", np.sort(arr2d,axis=1))
print("Sort array default\n", np.sort(arr2d))

Original array is
 [[3 1]
 [2 3]
 [1 2]]
Sort array column wise
 [[1 1]
 [2 2]
 [3 3]]
Sort array row wise
 [[1 3]
 [2 3]
 [1 2]]
Sort array default
 [[1 3]
 [2 3]
 [1 2]]


### Boolean filter

In [14]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(arr1d % 2 == 0)
print(arr1d[arr1d % 2 == 0])
print(arr1d > 5)
print(arr1d[(arr1d > 5)])
print((arr1d > 4) & (arr1d < 10))
print(arr1d[(arr1d > 4) & (arr1d < 10)])
print(~(arr1d > 4) & (arr1d < 10))

[False  True  True False  True False  True  True]
[ 4  6  8 10  6]
[False False  True  True  True  True  True  True]
[ 6  7  8  9 10  6]
[False False  True  True  True  True False  True]
[6 7 8 9 6]
[ True  True False False False False False False]


### where filter

In [20]:
arr1d = np.array([1,4,6,7,8,9,10,6])
print(np.where(arr1d > 6))
print(arr1d[np.where(arr1d > 6)])
print(np.where(arr1d > 6, True, False))

(array([3, 4, 5, 6]),)
[ 7  8  9 10]
[False False False  True  True  True  True False]


### Append Vs concatenate Vs insert

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
# print(np.append(arr1,arr2))
# print(np.concatenate((arr1,arr2))) # arrays passed as tuple

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
print(np.append(arr1,arr2))
print("Output of append\n",np.append(arr1,arr2,axis=0))
print("Output of concatenate\n",np.concatenate((arr1,arr2),axis=0))
print(np.append(arr1,arr2,axis=1))
print(np.concatenate((arr1,arr2),axis=1))

arr = np.array([[1,2],[3,4]])
print(np.insert(arr,0,[5,6],axis=0))
print(np.insert(arr,1,[5,6],axis=0))
print(np.insert(arr,2,[5,6],axis=0))
print(np.insert(arr,0,[5,6],axis=1)) # NumPy reshapes it internally to (1, 2)
print(np.insert(arr,2,[5,6],axis=1))
print(np.insert(arr,2,[5,6],axis=None))
print(np.concatenate((arr,[[5,6]]),axis=0))
print(np.concatenate((arr,[[5],[6]]),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6]
Output of append
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Output of concatenate
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[5 6]
 [1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[5 1 2]
 [6 3 4]]
[[1 2 5]
 [3 4 6]]
[1 2 5 6 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


### vstack and hstack

In [40]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [46]:
### mathematical operations
arr = np.random.randint(10,60,8)
print(arr)
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))


[30 29 40 56 21 34 31 15]
256
56
15
32.0
11.554220008291344
133.5


### Mathematical functions

In [58]:
arr1 = np.array([3,4,5])
arr2 = np.array([2,3,1])
print(arr1 * 2)
print(arr1 * arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

arr3 = np.random.randint(10,50,(3,3))
print("value of arr3 is \n",arr3)
print(arr3 * 2)
print(arr3 * arr1)


[ 6  8 10]
[ 6 12  5]
[5 7 6]
[1 1 4]
[1.5        1.33333333 5.        ]
[ 9 64  5]
value of arr3 is 
 [[45 39 25]
 [48 21 22]
 [19 37 40]]
[[90 78 50]
 [96 42 44]
 [38 74 80]]
[[135 156 125]
 [144  84 110]
 [ 57 148 200]]


### vectorisation

In [4]:
arr = np.array(["john","doe"])
vec_up = np.vectorize(str.lower)
print(vec_up(arr))


['john' 'doe']


### insert
### delete
### split (np.split(), np.hsplit(), np.vsplit())

In [24]:
arr = np.array([1,5,6,8,])
print(np.insert(arr, 1, 15))
print(np.delete(arr, 0))
print(np.split(arr,2))

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8]])

print(np.split(arr, 2, axis=1))



[ 1 15  5  6  8]
[5 6 8]
[array([1, 5]), array([6, 8])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
