In [2]:
import numpy as np
print(np.__version__)

2.3.2


create arrays \
Practice with Attributes  \
Practice creating numpy arrays using standard methods  \
Indexing and Slicing  \
Fancy Indexing \
Reshaping, flatten, ravel  \
sorting  \
Filter and Filter with mask  \
Filter with where clause  \
concatenate, vstack, hstack \
np.delete \


### Array creation

In [5]:
array_0 = np.array(10)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

10
<class 'numpy.ndarray'>
0
()
int64
1
8
8


In [ ]:
array_0 = np.arange(1,10,1)
print(array_0)
print(type(array_0))
print(array_0.ndim)
print(array_0.shape)
print(array_0.dtype)
print(array_0.size)
print(array_0.itemsize)
print(array_0.nbytes)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(9,)
int64
9
8
72


In [6]:
array_2 = np.random.randint(1,10,(2,3))
print(array_2)
print(type(array_2))
print(array_2.ndim)
print(array_2.shape)
print(array_2.dtype)
print(array_2.size)
print(array_2.itemsize)
print(array_2.nbytes)

[[1 5 5]
 [6 4 9]]
<class 'numpy.ndarray'>
2
(2, 3)
int64
6
8
48


In [3]:
array_zeros = np.zeros((5,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
array_ones = np.ones((5,4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
array_full = np.full((3,4),10)
array_full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [7]:
array_arange = np.arange(1,10,2)
array_arange

array([1, 3, 5, 7, 9])

In [8]:
array_linspace = np.linspace(1,10,2)
array_linspace

array([ 1., 10.])

In [10]:
array_random_random = np.random.random((2,4))
array_random_random

array([[0.26486404, 0.46609689, 0.21227865, 0.81591537],
       [0.61963626, 0.10217041, 0.03562537, 0.54715583]])

In [12]:
array_random_rand = np.random.rand(2,4)
array_random_rand

array([[0.23004184, 0.71590869, 0.95053961, 0.38450495],
       [0.76438243, 0.24021762, 0.16013896, 0.59106192]])

In [13]:
array_random_randint = np.random.randint(1,5,(5,6))
array_random_randint

array([[4, 1, 1, 4, 4, 3],
       [4, 2, 3, 1, 3, 3],
       [4, 3, 3, 2, 1, 3],
       [1, 3, 3, 4, 3, 1],
       [1, 1, 2, 1, 3, 2]])

In [16]:
array_eye = np.eye(4,4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
array_empty = np.empty((3,5))
array_empty

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [19]:
array_empty.shape


(3, 5)

In [22]:
array_empty[2][4]

np.float64(0.4472135954999579)

In [24]:
array_empty[2,4]

np.float64(0.4472135954999579)

In [ ]:
fancy_indexing = [3,4]
array_empty[fancy_indexing]

array([], shape=(0, 3, 5), dtype=float64)