In [4]:
import numpy as np
print(np.__version__)

2.3.2


In [6]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr = np.ones((2,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(type(arr))
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)
float64
<class 'numpy.ndarray'>
6
8
48


In [15]:
arr = np.full((4,5),8)
print(arr)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [21]:
arr = np.arange(1,10,2)
print(arr)
arr = np.random.random((4,5))
print(arr)
arr = np.random.randint(1,5,(3,4))
print(arr)

[1 3 5 7 9]
[[0.89291293 0.09578861 0.93694404 0.97451974 0.87928214]
 [0.72724862 0.16477983 0.24018419 0.37513166 0.39556399]
 [0.44259226 0.65689258 0.66306714 0.08857607 0.5499166 ]
 [0.90824983 0.45676324 0.89839841 0.3228975  0.01695287]]
[[1 2 4 4]
 [1 4 3 1]
 [4 3 1 3]]


In [24]:
arr = np.eye(5)
print(arr)
arr = np.linspace(1,5,10)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [26]:
print(arr.sum())
print(np.sum(arr))
print(arr.mean())
print(np.mean(arr))
print(np.median(arr))
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.var())


30.0
30.0
3.0
3.0
3.0
5.0
1.0
1.2765694770084506
1.6296296296296293
